# -*- coding: utf-8 -*-
"""projet_integre_1(1) (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111mrkzoJCNgHfqesbeDthDMmsRbUnkLC

1. Chargement des Données
Chargement du fichier Excel dans un DataFrame Pandas et examination des premières lignes pour bien comprendre sa structure.
"""

import pandas as pd

# Chargement du fichier Excel
df = pd.read_excel('modified_smartphone_survey_data (1).xlsx')

# Affichage des premières lignes
df.head()

df = df.drop(columns=['Mental_Health_Status'])

"""2. Prétraitement des Données
Le prétraitement consiste à nettoyer et préparer les données pour l’analyse. Voici les étapes recommandées :

2.1 Vérification et Gestion des Valeurs Manquantes
Vérifiez s'il y a des valeurs manquantes.
"""

# Vérification des valeurs manquantes
missing_values = df.isnull().sum()

# Affichage des colonnes avec valeurs manquantes
print("Valeurs manquantes par colonne :\n", missing_values)

df.head()

"""2.2 Codage des Variables Catégoriques
Convertissez les variables catégoriques en variables numériques pour une utilisation dans des modèles de machine learning. Utilisez l’encodage de variables catégoriques avec pd.get_dummies pour les variables avec plusieurs catégories ou LabelEncoder pour des catégories binaires.
"""

# Encodage des variables catégoriques
from sklearn.preprocessing import StandardScaler, LabelEncoder
categorical_columns = ['Check_Times_Per_Day', 'Primary_Use', 'Sleep_Quality', 'Digital_Wellness_Features', 'Anxiety_Level']
for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

"""2.3 Standardisation des Variables Numériques
Pour certaines analyses (comme l'analyse en composantes principales ou les algorithmes de machine learning), il est utile de standardiser les données numériques.
"""

df.head()

from sklearn.preprocessing import StandardScaler

# Normalisation des colonnes numériques
scaler = StandardScaler()
df[['Hours_on_Smartphone', 'Notifications_Per_Day', 'Hours_of_Sleep']] = scaler.fit_transform(df[['Hours_on_Smartphone', 'Notifications_Per_Day', 'Hours_of_Sleep']])

"""3. Analyse Exploratoire des Données (EDA)
3.1 Statistiques Descriptives
Commencez par examiner les statistiques descriptives pour obtenir un aperçu des moyennes, médianes, min, max, et écart-type.
"""

# Statistiques descriptives
df.describe()

"""3.2 Distribution des Variables
Utilisez des histogrammes pour visualiser les distributions des variables numériques, ce qui permet de détecter les anomalies et la distribution générale des réponses.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Distribution des heures passées sur le smartphone
sns.histplot(df['Hours_on_Smartphone'], bins=10)
plt.title("Distribution des heures passées sur le smartphone")
plt.show()

"""3.3 Analyse des Corrélations
Calculez la matrice de corrélation pour voir les relations entre les variables numériques.

3.3 Analyse des Corrélations
Calculez la matrice de corrélation pour voir les relations entre les variables numériques.
"""

# Calcul de la matrice de corrélation avec toutes les colonnes numériques
correlation_matrix = df.corr()

# Affichage de la matrice de corrélation
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Matrice de corrélation")
plt.show()

"""3.4 Comparaison de la Santé Mentale et des Facteurs de Smartphone
Visualisez la relation entre la variable cible Mental_Health_Target et d’autres variables clés, par exemple en utilisant des graphiques à barres ou des boîtes à moustaches.
"""

# Relation entre l'anxiété liée à l'utilisation du smartphone et la santé mentale
sns.boxplot(x='Mental_Health_Target', y='Hours_on_Smartphone', data=df)
plt.title("Impact de l'utilisation du smartphone sur la santé mentale")
plt.show()

df.head()

# Filter data for groups
group_good = df[df['Sleep_Quality'] == 'Good']['Hours_on_Smartphone']
group_poor = df[df['Sleep_Quality'] == 'Poor']['Hours_on_Smartphone']

from scipy.stats import ttest_ind

# Perform the t-test
stat, p = ttest_ind(group_good, group_poor)

print('Statistic:', stat)
print('P-value:', p)

# Interpret the p-value
alpha = 0.05  # Significance level
if p < alpha:
    print("Reject the null hypothesis: Hours_on_Smartphone significantly affects Sleep_Quality.")
else:
    print("Fail to reject the null hypothesis: No significant effect of Hours_on_Smartphone on Sleep_Quality.")

# Convert Anxiety_Level to categorical groups
# Assuming Anxiety_Level has categories like 'Low', 'Medium', 'High', we create two groups for comparison
group_low = df[df['Anxiety_Level'] == 'Low']['Notifications_Per_Day']
group_high = df[df['Anxiety_Level'] == 'Large']['Notifications_Per_Day']

# Perform the t-test
stat, p = ttest_ind(group_low, group_high)

# Output the results
print('Statistic:', stat)
print('P-value:', p)

# Interpret the p-value
alpha = 0.05  # Significance level
if p < alpha:
    print("Reject the null hypothesis: Notifications_Per_Day significantly affects Anxiety_Level.")
else:
    print("Fail to reject the null hypothesis: No significant effect of Notifications_Per_Day on Anxiety_Level.")

# Convert Mental_Health_Status into two groups for analysis
# For example: 'Good' vs. 'Poor' or 'Stable' vs. 'Unstable'
group_good = df[df['Mental_Health_Target'] == '0']['Hours_of_Sleep']
group_poor = df[df['Mental_Health_Target'] == '1']['Hours_of_Sleep']

# Perform the t-test
stat, p = ttest_ind(group_good, group_poor)

# Output the results
print('Statistic:', stat)
print('P-value:', p)

# Interpret the p-value
alpha = 0.05  # Significance level
if p < alpha:
    print("Reject the null hypothesis: Hours_of_Sleep significantly affects Mental_Health_Status.")
else:
    print("Fail to reject the null hypothesis: No significant effect of Hours_of_Sleep on Mental_Health_Status.")

# Perform a t-test to compare Anxiety_Level between groups with and without Digital_Wellness_Features
# Assuming 'Digital_Wellness_Features' is binary (1 = enabled, 0 = disabled)
group_with_features = df[df['Digital_Wellness_Features'] == 1]['Anxiety_Level']
group_without_features = df[df['Digital_Wellness_Features'] == 0]['Anxiety_Level']

# Perform t-test
stat, p = ttest_ind(group_with_features, group_without_features)

# Output the result
print('Statistic:', stat)
print('P-value:', p)

# Interpret the result
if p < 0.05:
    print("Reject the null hypothesis: Digital wellness features significantly reduce anxiety level.")
else:
    print("Fail to reject the null hypothesis: Digital wellness features do not significantly reduce anxiety level.")

# Remplacer les valeurs non numériques par NaN
df['Check_Times_Per_Day'] = pd.to_numeric(df['Check_Times_Per_Day'], errors='coerce')

# Supprimer les lignes avec des valeurs manquantes
df = df.dropna(subset=['Check_Times_Per_Day'])

# Exemple : Comparaison entre deux groupes (par exemple, 'Good' vs 'Poor' pour Sleep_Quality)
group_good = df[df['Sleep_Quality'] == 'Good']['Check_Times_Per_Day']
group_poor = df[df['Sleep_Quality'] == 'Poor']['Check_Times_Per_Day']

# Effectuer le test t de Student
stat, p = ttest_ind(group_good, group_poor)

# Output the result
print('Statistic:', stat)
print('P-value:', p)

# Interpréter les résultats
alpha = 0.05  # Niveau de signification
if p < alpha:
    print("Rejeter H₀ : Les Check_Times_Per_Day ont un impact significatif sur Hours_of_Sleep.")
else:
    print("Ne pas rejeter H₀ : Les Check_Times_Per_Day n'ont pas d'impact significatif sur Hours_of_Sleep.")

# Vérifier s'il y a des valeurs manquantes dans les deux colonnes
print(df[['Check_Times_Per_Day', 'Sleep_Quality']].isna().sum())

# Supprimer les lignes contenant des NaN dans les colonnes pertinentes
df_cleaned = df.dropna(subset=['Check_Times_Per_Day', 'Sleep_Quality'])

# Vérifier à nouveau
print(df_cleaned[['Check_Times_Per_Day', 'Sleep_Quality']].isna().sum())

# Vérifier les valeurs uniques dans la colonne 'Sleep_Quality'
print(df_cleaned['Sleep_Quality'].unique())

# Si nécessaire, normaliser ou corriger les valeurs
df_cleaned['Sleep_Quality'] = df_cleaned['Sleep_Quality'].replace({'bad': 'Poor', 'good': 'Good'})

# Exemple : Comparaison entre deux groupes (par exemple, 'Good' vs 'Poor' pour Sleep_Quality)
group_with_wellness = df[df['Digital_Wellness_Features'] == 'Yes']['Sleep_Quality']
group_without_wellness = df[df['Digital_Wellness_Features'] == 'No']['Sleep_Quality']

# Effectuer le test t de Student
stat, p = ttest_ind(group_with_wellness, group_without_wellness)

# Afficher les résultats
print('Statistic:', stat)
print('P-value:', p)

# Interpréter les résultats
alpha = 0.05  # Niveau de signification
if p < alpha:
    print("Reject the null hypothesis: Digital wellness features significantly reduce sleep quality")
else:
    print("Fail to reject the null hypothesis: Digital wellness features do not significantly reduce sleep quality")

# Définir les caractéristiques (X) et la cible (y)
X = df.drop('Mental_Health_Target', axis=1)
y = df['Mental_Health_Target']

# Diviser les données en ensembles d'entraînement et de test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Importation des bibliothèque
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialisation du modèle de régression logistique
logreg = LogisticRegression(random_state=42)

# Entraînement du modèle
logreg.fit(X_train, y_train)

# Prédictions
logreg_preds = logreg.predict(X_test)

# Accuracy
logreg_accuracy = accuracy_score(y_test, logreg_preds)

# Affichage des résultats
print("Logistic Regression Accuracy: {:.2f}%".format(logreg_accuracy * 100))

# Rapport de classification
print("\nClassification Report - Logistic Regression:")
print(classification_report(y_test, logreg_preds))

# prompt: #1- Linear Regression: # Initialize and train the Linear Regression model

# Initialize and train the Linear Regression model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the Linear Regression model
linreg = LinearRegression()

# Train the model
linreg.fit(X_train, y_train)

# Make predictions on the test set
linreg_preds = linreg.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, linreg_preds)
r2 = r2_score(y_test, linreg_preds)

# Print the results
print("Linear Regression Mean Squared Error:", mse)
print("Linear Regression R-squared:", r2)

"""MSE = 0.225 : L'erreur de prédiction moyenne au carré est faible, ce qui est positif, mais cela ne garantit pas que le modèle est performant (car cela dépend de l'échelle des données).

R² = 0.0896 : Le modèle n'explique qu'une petite partie (9%) de la variance des données. Cela suggère que :
Soit le modèle de régression linéaire n'est pas adapté aux données.
Soit les données manquent de corrélation linéaire, ce qui limite la performance du modèle

### Logistic Regression
"""

# prompt: Logistic Regression:

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load the data
df = pd.read_excel('modified_smartphone_survey_data (1).xlsx')

# Preprocessing (assuming previous preprocessing steps are correct and relevant)
df = df.drop(columns=['Mental_Health_Status'])
categorical_columns = ['Check_Times_Per_Day', 'Primary_Use', 'Sleep_Quality', 'Digital_Wellness_Features', 'Anxiety_Level']
for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

scaler = StandardScaler()
numerical_cols = ['Hours_on_Smartphone', 'Notifications_Per_Day', 'Hours_of_Sleep']
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])


# Handle missing values in 'Check_Times_Per_Day' more robustly
df['Check_Times_Per_Day'] = pd.to_numeric(df['Check_Times_Per_Day'], errors='coerce')
df.dropna(subset=['Check_Times_Per_Day'], inplace=True)

# Ensure 'Sleep_Quality' and 'Digital_Wellness_Features' are correctly encoded
df['Sleep_Quality'] = df['Sleep_Quality'].replace({'bad': 'Poor', 'good': 'Good'}) # handle inconsistent values
le = LabelEncoder()
df['Digital_Wellness_Features'] = le.fit_transform(df['Digital_Wellness_Features'])
df['Anxiety_Level'] = le.fit_transform(df['Anxiety_Level'])


# Define features (X) and target (y)
X = df.drop('Mental_Health_Target', axis=1)
y = df['Mental_Health_Target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Logistic Regression
logreg = LogisticRegression(random_state=42)
logreg.fit(X_train, y_train)
logreg_preds = logreg.predict(X_test)
logreg_accuracy = accuracy_score(y_test, logreg_preds)

print("Logistic Regression Accuracy: {:.2f}%".format(logreg_accuracy * 100))
print(classification_report(y_test, logreg_preds))

# Linear Regression (for comparison)
linreg = LinearRegression()
linreg.fit(X_train, y_train)
linreg_preds = linreg.predict(X_test)
mse = mean_squared_error(y_test, linreg_preds)
r2 = r2_score(y_test, linreg_preds)

print("\nLinear Regression Mean Squared Error:", mse)
print("Linear Regression R-squared:", r2)

"""### Mean Squared Error (MSE) = 0.225 :

L'erreur quadratique moyenne entre les valeurs réelles et prédites est 0.225. Cela signifie que, en moyenne, la différence entre les prédictions et les valeurs réelles est assez faible, mais cela dépend de l'échelle des données.
### R-squared (R²) = 0.0896 (≈ 9%) :
Ce modèle explique seulement 9% de la variance des données cibles.
Cela montre que le modèle de régression linéaire n'est pas performant. Il y a beaucoup d'informations dans les données que ce modèle ne parvient pas à capturer.

# Linear Discriminant Analysis (LDA)
"""

# prompt:  Linear Discriminant Analysis (LDA)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the LDA model
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

# Make predictions on the test set
lda_preds = lda.predict(X_test)

# Evaluate the LDA model
lda_accuracy = accuracy_score(y_test, lda_preds)
print("\nLDA Accuracy: {:.2f}%".format(lda_accuracy * 100))
print(classification_report(y_test, lda_preds))

"""Accuracy : 70% → Le modèle prédit correctement 70% des cas.

Classe 0 : Très bien prédite (précision = 65%, rappel = 100%).

Classe 1 : Moins bien prédite (précision = 100%, rappel = 33%).

### Random Forest Classifier
"""

# prompt:  Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)  # You can adjust hyperparameters here
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
rf_predictions = rf_classifier.predict(X_test)

# Evaluate the model
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("\nRandom Forest Accuracy: {:.2f}%".format(rf_accuracy * 100))
print(classification_report(y_test, rf_predictions))
# Evaluate the classifier
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, rf_predictions))
print(classification_report(y_test, rf_predictions))

"""### Random Forest Regressor"""

# prompt: Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor
# ... (your existing code)

# Initialize and train the Random Forest Regressor
rf_regressor = RandomForestRegressor(random_state=42)  # You can adjust hyperparameters here
rf_regressor.fit(X_train, y_train)

# Make predictions on the test set
rf_predictions = rf_regressor.predict(X_test)

# Evaluate the model (example using Mean Squared Error and R-squared)
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, rf_predictions)
r2 = r2_score(y_test, rf_predictions)

print("\nRandom Forest Regressor Mean Squared Error:", mse)
print("Random Forest Regressor R-squared:", r2)

logreg = LogisticRegression(random_state=42, class_weight='balanced')

from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=1)  # Réduire à une seule dimension
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'],
    'max_iter': [100, 200, 500]
}

grid_search = GridSearchCV(LogisticRegression(random_state=42), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_

from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs', 'saga'],
    'max_iter': [100, 200, 500]
}

rand_search = RandomizedSearchCV(LogisticRegression(random_state=42), param_distributions=param_dist, n_iter=10, cv=5, scoring='accuracy', random_state=42)
rand_search.fit(X_train, y_train)

best_model = rand_search.best_estimator_

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Créer un pipeline avec normalisation et régression logistique
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(random_state=42, class_weight='balanced'))
])

pipeline.fit(X_train, y_train)

# Prédiction et évaluation
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")





